#!/bin/bash

set -u

# User role and management operations

if grep-dctrl -q -XFStatus "install ok installed" -a \
   -XFPackage docker-ce $1/var/lib/dpkg/status ; then
   if igconf isy meta_docker_trust_user1 ; then
      chroot $1 sh -c "adduser $KSconf_device_user docker"
   fi
fi

if grep-dctrl -q -XFStatus "install ok installed" -a \
   -XFPackage openssh-server $1/var/lib/dpkg/status ; then
   if [ -d $1/home/${KSconf_device_user}/.ssh ] ; then
      chroot $1 bash -- <<- EOCHROOT
      chown -R ${KSconf_device_user}:${KSconf_device_user} /home/${KSconf_device_user}/.ssh
      chmod 0700 /home/${KSconf_device_user}/.ssh
      if [ -f /home/${KSconf_device_user}/.ssh/authorized_keys ] ; then
         chmod 0600 /home/${KSconf_device_user}/.ssh/authorized_keys
      fi
EOCHROOT
   fi
fi
