#!/bin/bash

set -eu

# Install files
if [ -d $1/etc/initramfs-tools ] ; then
   for dir in ${IGIMAGE}/device/initramfs-tools \
              ${IGBOARD}/device/initramfs-tools \
              ../device/initramfs-tools ; do
      [[ -d "$dir" ]] || continue
      rsync --archive --ignore-existing "${dir}/" $1/etc/initramfs-tools
   done
fi

# Always make sure all initramfs are updated
if [ -s $1/etc/initramfs-tools/update-initramfs.conf ] ; then
   cp $1/etc/initramfs-tools/update-initramfs.conf $1/etc/initramfs-tools/update-initramfs.conf.bak
   sed -i 's/^update_initramfs=.*/update_initramfs=all/' $1/etc/initramfs-tools/update-initramfs.conf
   chroot $1 update-initramfs -u
   mv -f $1/etc/initramfs-tools/update-initramfs.conf.bak $1/etc/initramfs-tools/update-initramfs.conf
fi
