#!/bin/bash

set -eu

# Currently only initramfs-tools is supported
if ! grep-dctrl -q -XFStatus "install ok installed" -a \
   -XFPackage initramfs-tools $1/var/lib/dpkg/status ; then
   exit 0
fi

# Install files
for dir in ${IGIMAGE}/device/initramfs-tools \
           ${IGDEVICE}/device/initramfs-tools \
           ../device/initramfs-tools ; do
   [[ -d "$dir" ]] || continue
   rsync --archive --ignore-existing "${dir}/" $1/etc/initramfs-tools
done

# Always make sure all initramfs are updated
cp $1/etc/initramfs-tools/update-initramfs.conf $1/etc/initramfs-tools/update-initramfs.conf.bak
sed -i 's/^update_initramfs=.*/update_initramfs=all/' $1/etc/initramfs-tools/update-initramfs.conf
chroot $1 update-initramfs -u
mv -f $1/etc/initramfs-tools/update-initramfs.conf.bak $1/etc/initramfs-tools/update-initramfs.conf
