= rpi-image-gen

rpi-image-gen is a tool used to create custom software images for Raspberry Pi devices. rpi-image-gen runs best on a Raspberry Pi Host running up-to-date Raspberry Pi OS.

**For the tool used to create Raspberry Pi OS, please go to https://github.com/RPi-Distro/pi-gen**

**NOTE** 15th November 2024: rpi-image-gen is under active development. Please report issues at https://github.com/raspberrypi/rpi-image-gen

== Terminology

The following terms are used throughout this document:

*Host* The machine on which rpi-image-gen is executing. Analogous to GNU Build.

*Target* The machine on which the image generated by rpi-image-gen will execute. Analogous to GNU Host.

*Package* A collection of files and software resources, encapsulated in a known format, that constitute part of a larger software system.

== Getting started

----
git clone https://github.com/raspberrypi/rpi-image-gen.git
----

== Dependencies

To install the required Host dependencies for rpi-image-gen you should run:

----
install_deps.sh
----

The file `depends` contains a list of the dependencies required. The format of this file is `<tool>[:<debian-package>]`.

== Overview

rpi-image-gen is a root file system and image creation tool designed with a high degree of customisation, flexibility and control in mind. rpi-image-gen uses bdebstrap (https://github.com/bdrung/bdebstrap) and mmdebstrap (https://gitlab.mister-muffin.de/josch/mmdebstrap) for rootfs construction and genimage (https://github.com/pengutronix/genimage) for image creation. rpi-image-gen is a bash orientated scripting engine capable of producing software images with different on-disk partition layouts, file systems and profiles using collections of metadata and a defined flow of execution. It provides the means to create a highly customised software image for your Raspberry Pi device. rpi-image-gen is human readable, auditable and easy to use.

This readme will be updated in the very near future with further information.
