#!/bin/sh

# pkgs we need for our kiosk (cage from Debian is old and expects xwayland #293)
chroot $1 apt install -y cage xwayland chromium

# We'll run chromium like this
APP="/usr/bin/chromium-browser https://raspberrypi.com https://time.is/London --kiosk --noerrdialogs --disable-infobars --no-first-run --ozone-platform=wayland --enable-features=OverlayScrollbar --start-maximized"

# Write out our systemd kiosk service
cat ../kiosk.service.tpl | sed \
   -e "s|<KIOSK_USER>|$IGconf_device_user1name|g" \
   -e "s|<KIOSK_RUNDIR>|\/home\/$IGconf_device_user1name|g" \
   -e "s|<KIOSK_APP>|$APP|g" \
   > $1/etc/systemd/system/kiosk.service

# Enable the kiosk service so it starts automatically
$BDEBSTRAP_HOOKS/enable-units "$1" kiosk
