#!/bin/sh

set -eu

# Install slot rules
install -m 0644 -D ../device/slot.rules $1/etc/udev/rules.d/90-rpi-slot.rules


# Install provision map
if igconf isset image_pmap ; then
   cp ../device/provisionmap-${IGconf_image_pmap}.json ${IGconf_sys_outputdir}/provisionmap.json
else
   die "No pmap. Unable to generate slot mapping."
fi


# Generate pre-defined UUIDs
BOOTA_LABEL=$(uuidgen | sed 's/-.*//' | tr 'a-f' 'A-F')
BOOTA_UUID=$(echo "$BOOTA_LABEL" | sed 's/^\(....\)\(....\)$/\1-\2/')
BOOTB_LABEL=$(uuidgen | sed 's/-.*//' | tr 'a-f' 'A-F')
BOOTB_UUID=$(echo "$BOOTB_LABEL" | sed 's/^\(....\)\(....\)$/\1-\2/')
SYSTEMA_UUID=$(uuidgen)
SYSTEMB_UUID=$(uuidgen)
CRYPT_UUID=$(uuidgen)

rm -f ${IGconf_sys_outputdir}/img_uuids
for v in BOOTA_LABEL BOOTA_UUID BOOTB_LABEL BOOTB_UUID SYSTEMA_UUID SYSTEMB_UUID CRYPT_UUID; do
    eval "val=\$$v"
    echo "$v=$val" >> "${IGconf_sys_outputdir}/img_uuids"
done


# Populate PMAP UUIDs
sed -i \
   -e "s|<BOOTA_UUID>|$BOOTA_UUID|g" \
   -e "s|<BOOTB_UUID>|$BOOTB_UUID|g" \
   -e "s|<SYSTEMA_UUID>|$SYSTEMA_UUID|g" \
   -e "s|<SYSTEMB_UUID>|$SYSTEMB_UUID|g" \
   -e "s|<CRYPT_UUID>|$CRYPT_UUID|g" ${IGconf_sys_outputdir}/provisionmap.json


# Generate slot helper
mkslot-helper ${IGconf_sys_outputdir}/provisionmap.json > $1/usr/bin/rpi-slot
chmod +x $1/usr/bin/rpi-slot


# Hint to initramfs-tools we have an ext4 rootfs
sed -i "s|FSTYPE=\([^ ]*\)|FSTYPE=ext4|" $1/etc/initramfs-tools/initramfs.conf
