#!/bin/sh

set -u

exec 2>/dev/null

slot=$(grep -oP 'root=/dev/disk/by-label/ROOT\K[A-B]' /proc/cmdline)
case $slot in
   A)
      active=A
      other=B
      ;;
   B)
      active=B
      other=A
      ;;
   *)
      exit 1
      ;;
esac

if [ $# -eq 0 ] ; then
   echo "$active"
elif [ $# -eq 1 ] ; then
   case $1 in
      active) echo "$active" ;;
      other) echo "$other" ;;
      *) exit 1 ;;
   esac
else
   false
fi
